"""empty message

Revision ID: 06cbb5ff4bbe
Revises: c0237a5bf072
Create Date: 2026-05-01 15:02:16.539296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06cbb5ff4bbe'
down_revision = 'c0237a5bf072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_mantenimiento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proximo_mantenimiento', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_detalles_mantenimiento_proximo_mantenimiento'), ['proximo_mantenimiento'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_mantenimiento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detalles_mantenimiento_proximo_mantenimiento'))
        batch_op.drop_column('proximo_mantenimiento')

    # ### end Alembic commands ###
