"""add fecha_reactivacion to equipos_instalados

Revision ID: 4c008f862493
Revises: 06cbb5ff4bbe
Create Date: 2026-05-11 22:46:04.382044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c008f862493'
down_revision = '06cbb5ff4bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos_instalados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_reactivacion', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos_instalados', schema=None) as batch_op:
        batch_op.drop_column('fecha_reactivacion')

    # ### end Alembic commands ###
