"""intervalo_nominal en Componente, simplificar TipoEquipoComponente

Revision ID: c0237a5bf072
Revises: 
Create Date: 2026-05-01 10:27:02.278742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0237a5bf072'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('componentes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intervalo_nominal', sa.Integer(), nullable=False))
        batch_op.drop_column('unidad')

    with op.batch_alter_table('tipo_equipo_componente', schema=None) as batch_op:
        batch_op.drop_column('intervalo_nominal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_equipo_componente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intervalo_nominal', mysql.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('componentes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidad', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))
        batch_op.drop_column('intervalo_nominal')

    # ### end Alembic commands ###
