"""add motivo_anulacion to mantenimientos

Revision ID: daa06afda422
Revises: 4c008f862493
Create Date: 2026-05-31 19:01:23.018745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa06afda422'
down_revision = '4c008f862493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mantenimientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo_anulacion', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mantenimientos', schema=None) as batch_op:
        batch_op.drop_column('motivo_anulacion')

    # ### end Alembic commands ###
